import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import simpleImportSort from 'eslint-plugin-simple-import-sort';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    plugins: { 'simple-import-sort': simpleImportSort },
    rules: {
      // Import order can cause dependency issues; local files and CSS go last.
      'simple-import-sort/imports': [
        'error',
        {
          groups: [
            // Side-effect imports first (`server-only`, polyfills).
            ['^\\u0000'],
            // Node builtins, then packages.
            ['^node:', '^@?\\w'],
            // Aliased project modules.
            ['^@/'],
            // Relative modules, then CSS, last.
            ['^\\.', '^.+\\.css$'],
          ],
        },
      ],
      'simple-import-sort/exports': 'error',
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Vendored shadcn components: regenerated by the CLI, not hand-edited.
    'src/components/ui/**',
  ]),
]);

export default eslintConfig;
